### ISSUE TITLE
This doesn't work..

### ISSUE THREAD

**Issue by BigBobDalton** [AutoCONFIG/RTL88x2BU-OpenWRT#2]
make menuconfig
Makefile:22: /package.mk: No such file or directory
make: *** No rule to make target '/package.mk'.  Stop.

**Comment by AutoCONFIG** [comment]
Hi, I'm sorry to tell you that this code repository was abandoned. Because this WiFi-Adapter is old that can't support modern fast network of more than 200 megabytes, so I‘m not maintaining this resipository to support the latest version of OpenWrt.
If you want to use this device in OpenWrt, you can try this: [immortalwrt](https://github.com/immortalwrt/immortalwrt), there is an rt88x2bu driver in the “immortalwrt/package/kernel/rtl88x2bu/" directory.
